use super::flags::Flags;
use bitfield::Bit;

#[derive(Clone, Copy)]
pub enum AluOp {
    ADD,
    ADC,
    AND,
    BIT,
    CCF,
    CP,
    CPL,
    DAA,
    OR,
    RL,
    RLC,
    RR,
    RRC,
    RES,
    SBC,
    SCF,
    SET,
    SLA,
    SRA,
    SRL,
    SUB,
    SWAP,
    XOR,
}

pub fn execute(op: AluOp, x: u8, y: u8, flags: Flags) -> (u8, Flags) {
    use AluOp::*;

    let carry = flags.contains(Flags::Carry);

    match op {
        // Arithmetic
        ADD => arithmetic_op(x, y, false, u8::overflowing_add, false),
        ADC => arithmetic_op(x, y, carry, u8::overflowing_add, false),
        CP => {
            let (_, flags) = arithmetic_op(x, y, false, u8::overflowing_sub, true);
            (x, flags)
        }
        SBC => arithmetic_op(x, y, carry, u8::overflowing_sub, true),
        SUB => arithmetic_op(x, y, false, u8::overflowing_sub, true),

        // Logical
        AND => logical_op(x, y, true, |x, y| x & y),
        OR => logical_op(x, y, false, |x, y| x | y),
        XOR => logical_op(x, y, false, |x, y| x ^ y),

        // Shift
        RL => shift_op(x, carry, |x, carry| x << 1 | carry as u8, |x| x.bit(7)),
        RLC => shift_op(x, carry, |x, _| x.rotate_left(1), |x| x.bit(7)),
        RR => shift_op(
            x,
            carry,
            |x, carry| x >> 1 | (carry as u8) << 7,
            |x| x.bit(0),
        ),
        RRC => shift_op(x, carry, |x, _| x.rotate_right(1), |x| x.bit(0)),
        SLA => shift_op(x, carry, |x, _| x << 1, |x| x.bit(7)),
        SRA => shift_op(x, carry, |x, _| (x >> 1) | (x & 0x80), |x| x.bit(0)),
        SRL => shift_op(x, carry, |x, _| x >> 1, |x| x.bit(0)),
        SWAP => shift_op(x, carry, |x, _| (x << 4) | ((x >> 4) & 0xF), |_| false),

        // Bit Ops
        BIT => {
            let mut flags = (flags & Flags::Carry) | Flags::HalfCarry;
            flags.set(Flags::Zero, !x.bit(y as usize));

            (x, flags)
        }
        RES => (x & !(1 << y), flags),
        SET => (x | (1 << y), flags),

        // Misc
        CCF => {
            let carry = !flags.contains(Flags::Carry);

            let mut flags = flags & Flags::Zero;
            flags.set(Flags::Carry, carry);

            (x, flags)
        }
        CPL => (!x, flags | Flags::Subtract | Flags::HalfCarry),
        SCF => {
            let flags = (flags & Flags::Zero) | Flags::Carry;
            (x, flags)
        }

        DAA => daa(x, flags),
    }
}

fn arithmetic_op<T>(x: u8, y: u8, carry: bool, op: T, sub: bool) -> (u8, Flags)
where
    T: Fn(u8, u8) -> (u8, bool),
{
    let op = |x, y| {
        let (result, overflow) = op(x, y);
        let (result, carry_overflow) = op(result, carry as u8);

        (result, overflow || carry_overflow)
    };

    let (result, carry) = op(x, y);
    let half_carry = op(x & 0xF, y & 0xF).0 > 0xF;

    let mut flags = Flags::empty();
    flags.set(Flags::Zero, result == 0);
    flags.set(Flags::Subtract, sub);
    flags.set(Flags::HalfCarry, half_carry);
    flags.set(Flags::Carry, carry);

    (result, flags)
}

fn logical_op<T>(x: u8, y: u8, half_carry: bool, op: T) -> (u8, Flags)
where
    T: Fn(u8, u8) -> u8,
{
    let result = op(x, y);

    let mut flags = Flags::empty();
    flags.set(Flags::Zero, result == 0);
    flags.remove(Flags::Subtract);
    flags.set(Flags::HalfCarry, half_carry);
    flags.remove(Flags::Carry);

    (result, flags)
}

fn shift_op<T, U>(x: u8, carry: bool, op: T, carry_op: U) -> (u8, Flags)
where
    T: Fn(u8, bool) -> u8,
    U: Fn(u8) -> bool,
{
    let result = op(x, carry);
    let carry = carry_op(x);

    let mut flags = Flags::empty();
    flags.set(Flags::Zero, result == 0);
    flags.set(Flags::Carry, carry);

    (result, flags)
}

fn daa(a: u8, flags: Flags) -> (u8, Flags) {
    let mut adjust = if flags.contains(Flags::Carry) {
        0x60
    } else {
        0x00
    };

    if flags.contains(Flags::HalfCarry) {
        adjust |= 0x06;
    };

    let result = if !flags.contains(Flags::Subtract) {
        if a & 0x0F > 0x09 {
            adjust |= 0x06;
        };
        if a > 0x99 {
            adjust |= 0x60;
        };

        a.wrapping_add(adjust)
    } else {
        a.wrapping_sub(adjust)
    };

    let mut flags = flags;
    flags.set(Flags::Zero, result == 0);
    flags.remove(Flags::HalfCarry);
    flags.set(Flags::Carry, adjust >= 0x60);

    (result, flags)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn get_all_flag_combinations() -> Vec<Flags> {
        (0..16).map(|f| Flags::from_bits_truncate(f << 4)).collect()
    }

    fn test_alu_op(
        op: AluOp,
        x_values: &[u8],
        y_values: &[u8],
        flags: &[Flags],
        expected: &[(u8, Flags)],
    ) {
        let result: Vec<_> = x_values
            .iter()
            .flat_map(|x| y_values.iter().map(move |y| (x, y)))
            .flat_map(|(x, y)| flags.iter().map(move |flags| (x, y, flags)))
            .map(|(x, y, flags)| execute(op, *x, *y, *flags))
            .collect();

        assert_eq!(expected, result);
    }

    // Arithmetic
    #[test]
    fn test_add() {
        test_alu_op(
            AluOp::ADD,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty()],
            &[
                (0, Flags::Zero),
                (1, Flags::empty()),
                (127, Flags::empty()),
                (128, Flags::empty()),
                (255, Flags::empty()),
                (1, Flags::empty()),
                (2, Flags::empty()),
                (128, Flags::HalfCarry),
                (129, Flags::empty()),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (127, Flags::empty()),
                (128, Flags::HalfCarry),
                (254, Flags::HalfCarry),
                (255, Flags::empty()),
                (126, Flags::HalfCarry | Flags::Carry),
                (128, Flags::empty()),
                (129, Flags::empty()),
                (255, Flags::empty()),
                (0, Flags::Zero | Flags::Carry),
                (127, Flags::Carry),
                (255, Flags::empty()),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (126, Flags::HalfCarry | Flags::Carry),
                (127, Flags::Carry),
                (254, Flags::HalfCarry | Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_adc() {
        test_alu_op(
            AluOp::ADC,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (1, Flags::empty()),
                (1, Flags::empty()),
                (2, Flags::empty()),
                (127, Flags::empty()),
                (128, Flags::HalfCarry),
                (128, Flags::empty()),
                (129, Flags::empty()),
                (255, Flags::empty()),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (3, Flags::empty()),
                (128, Flags::HalfCarry),
                (129, Flags::HalfCarry),
                (129, Flags::empty()),
                (130, Flags::empty()),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::HalfCarry | Flags::Carry),
                (127, Flags::empty()),
                (128, Flags::HalfCarry),
                (128, Flags::HalfCarry),
                (129, Flags::HalfCarry),
                (254, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::empty()),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (126, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (128, Flags::empty()),
                (129, Flags::empty()),
                (129, Flags::empty()),
                (130, Flags::empty()),
                (255, Flags::empty()),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (1, Flags::Carry),
                (127, Flags::Carry),
                (128, Flags::HalfCarry | Flags::Carry),
                (255, Flags::empty()),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::HalfCarry | Flags::Carry),
                (126, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::Carry),
                (128, Flags::HalfCarry | Flags::Carry),
                (254, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_cp() {
        test_alu_op(
            AluOp::CP,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty()],
            &[
                (0, Flags::Zero | Flags::Subtract),
                (0, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Subtract | Flags::Carry),
                (0, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Subtract),
                (1, Flags::Zero | Flags::Subtract),
                (1, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Subtract | Flags::Carry),
                (1, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (127, Flags::Subtract),
                (127, Flags::Subtract),
                (127, Flags::Zero | Flags::Subtract),
                (127, Flags::Subtract | Flags::Carry),
                (127, Flags::Subtract | Flags::Carry),
                (128, Flags::Subtract),
                (128, Flags::Subtract | Flags::HalfCarry),
                (128, Flags::Subtract | Flags::HalfCarry),
                (128, Flags::Zero | Flags::Subtract),
                (128, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Subtract),
                (255, Flags::Subtract),
                (255, Flags::Subtract),
                (255, Flags::Subtract),
                (255, Flags::Zero | Flags::Subtract),
            ],
        );
    }

    #[test]
    fn test_sbc() {
        test_alu_op(
            AluOp::SBC,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero | Flags::Subtract),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (254, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (129, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Subtract | Flags::Carry),
                (127, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (
                    0,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (1, Flags::Subtract),
                (0, Flags::Zero | Flags::Subtract),
                (0, Flags::Zero | Flags::Subtract),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (130, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (129, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (129, Flags::Subtract | Flags::Carry),
                (128, Flags::Subtract | Flags::Carry),
                (2, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (127, Flags::Subtract),
                (126, Flags::Subtract),
                (126, Flags::Subtract),
                (125, Flags::Subtract),
                (0, Flags::Zero | Flags::Subtract),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Subtract | Flags::Carry),
                (254, Flags::Subtract | Flags::Carry),
                (128, Flags::Subtract | Flags::Carry),
                (127, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Subtract),
                (127, Flags::Subtract | Flags::HalfCarry),
                (127, Flags::Subtract | Flags::HalfCarry),
                (126, Flags::Subtract | Flags::HalfCarry),
                (1, Flags::Subtract | Flags::HalfCarry),
                (0, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (0, Flags::Zero | Flags::Subtract),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (129, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Subtract),
                (254, Flags::Subtract),
                (254, Flags::Subtract),
                (253, Flags::Subtract),
                (128, Flags::Subtract),
                (127, Flags::Subtract | Flags::HalfCarry),
                (127, Flags::Subtract),
                (126, Flags::Subtract),
                (0, Flags::Zero | Flags::Subtract),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_sub() {
        test_alu_op(
            AluOp::SUB,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty()],
            &[
                (0, Flags::Zero | Flags::Subtract),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (129, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Subtract | Flags::Carry),
                (1, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Subtract),
                (0, Flags::Zero | Flags::Subtract),
                (130, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (129, Flags::Subtract | Flags::Carry),
                (2, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (127, Flags::Subtract),
                (126, Flags::Subtract),
                (0, Flags::Zero | Flags::Subtract),
                (255, Flags::Subtract | Flags::Carry),
                (128, Flags::Subtract | Flags::Carry),
                (128, Flags::Subtract),
                (127, Flags::Subtract | Flags::HalfCarry),
                (1, Flags::Subtract | Flags::HalfCarry),
                (0, Flags::Zero | Flags::Subtract),
                (129, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Subtract),
                (254, Flags::Subtract),
                (128, Flags::Subtract),
                (127, Flags::Subtract),
                (0, Flags::Zero | Flags::Subtract),
            ],
        );
    }

    // Logical
    #[test]
    fn test_and() {
        test_alu_op(
            AluOp::AND,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty()],
            &[
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (1, Flags::HalfCarry),
                (1, Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (1, Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (1, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (128, Flags::HalfCarry),
                (128, Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (1, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (128, Flags::HalfCarry),
                (255, Flags::HalfCarry),
            ],
        );
    }

    #[test]
    fn test_or() {
        test_alu_op(
            AluOp::OR,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty()],
            &[
                (0, Flags::Zero),
                (1, Flags::empty()),
                (127, Flags::empty()),
                (128, Flags::empty()),
                (255, Flags::empty()),
                (1, Flags::empty()),
                (1, Flags::empty()),
                (127, Flags::empty()),
                (129, Flags::empty()),
                (255, Flags::empty()),
                (127, Flags::empty()),
                (127, Flags::empty()),
                (127, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (128, Flags::empty()),
                (129, Flags::empty()),
                (255, Flags::empty()),
                (128, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
            ],
        );
    }

    #[test]
    fn test_xor() {
        test_alu_op(
            AluOp::XOR,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty()],
            &[
                (0, Flags::Zero),
                (1, Flags::empty()),
                (127, Flags::empty()),
                (128, Flags::empty()),
                (255, Flags::empty()),
                (1, Flags::empty()),
                (0, Flags::Zero),
                (126, Flags::empty()),
                (129, Flags::empty()),
                (254, Flags::empty()),
                (127, Flags::empty()),
                (126, Flags::empty()),
                (0, Flags::Zero),
                (255, Flags::empty()),
                (128, Flags::empty()),
                (128, Flags::empty()),
                (129, Flags::empty()),
                (255, Flags::empty()),
                (0, Flags::Zero),
                (127, Flags::empty()),
                (255, Flags::empty()),
                (254, Flags::empty()),
                (128, Flags::empty()),
                (127, Flags::empty()),
                (0, Flags::Zero),
            ],
        );
    }

    // Shift
    #[test]
    fn test_rl() {
        test_alu_op(
            AluOp::RL,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (1, Flags::empty()),
                (0, Flags::Zero),
                (1, Flags::empty()),
                (0, Flags::Zero),
                (1, Flags::empty()),
                (0, Flags::Zero),
                (1, Flags::empty()),
                (0, Flags::Zero),
                (1, Flags::empty()),
                (2, Flags::empty()),
                (3, Flags::empty()),
                (2, Flags::empty()),
                (3, Flags::empty()),
                (2, Flags::empty()),
                (3, Flags::empty()),
                (2, Flags::empty()),
                (3, Flags::empty()),
                (2, Flags::empty()),
                (3, Flags::empty()),
                (254, Flags::empty()),
                (255, Flags::empty()),
                (254, Flags::empty()),
                (255, Flags::empty()),
                (254, Flags::empty()),
                (255, Flags::empty()),
                (254, Flags::empty()),
                (255, Flags::empty()),
                (254, Flags::empty()),
                (255, Flags::empty()),
                (0, Flags::Zero | Flags::Carry),
                (1, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (1, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (1, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (1, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (1, Flags::Carry),
                (254, Flags::Carry),
                (255, Flags::Carry),
                (254, Flags::Carry),
                (255, Flags::Carry),
                (254, Flags::Carry),
                (255, Flags::Carry),
                (254, Flags::Carry),
                (255, Flags::Carry),
                (254, Flags::Carry),
                (255, Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_rlc() {
        test_alu_op(
            AluOp::RLC,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (1, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_rr() {
        test_alu_op(
            AluOp::RR,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (128, Flags::empty()),
                (0, Flags::Zero),
                (128, Flags::empty()),
                (0, Flags::Zero),
                (128, Flags::empty()),
                (0, Flags::Zero),
                (128, Flags::empty()),
                (0, Flags::Zero),
                (128, Flags::empty()),
                (0, Flags::Zero | Flags::Carry),
                (128, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (128, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (128, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (128, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (128, Flags::Carry),
                (63, Flags::Carry),
                (191, Flags::Carry),
                (63, Flags::Carry),
                (191, Flags::Carry),
                (63, Flags::Carry),
                (191, Flags::Carry),
                (63, Flags::Carry),
                (191, Flags::Carry),
                (63, Flags::Carry),
                (191, Flags::Carry),
                (64, Flags::empty()),
                (192, Flags::empty()),
                (64, Flags::empty()),
                (192, Flags::empty()),
                (64, Flags::empty()),
                (192, Flags::empty()),
                (64, Flags::empty()),
                (192, Flags::empty()),
                (64, Flags::empty()),
                (192, Flags::empty()),
                (127, Flags::Carry),
                (255, Flags::Carry),
                (127, Flags::Carry),
                (255, Flags::Carry),
                (127, Flags::Carry),
                (255, Flags::Carry),
                (127, Flags::Carry),
                (255, Flags::Carry),
                (127, Flags::Carry),
                (255, Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_rrc() {
        test_alu_op(
            AluOp::RRC,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (128, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (191, Flags::Carry),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_sla() {
        test_alu_op(
            AluOp::SLA,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (2, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (254, Flags::empty()),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
                (254, Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_sra() {
        test_alu_op(
            AluOp::SRA,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (192, Flags::empty()),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
                (255, Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_srl() {
        test_alu_op(
            AluOp::SRL,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (63, Flags::Carry),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (64, Flags::empty()),
                (127, Flags::Carry),
                (127, Flags::Carry),
                (127, Flags::Carry),
                (127, Flags::Carry),
                (127, Flags::Carry),
                (127, Flags::Carry),
                (127, Flags::Carry),
                (127, Flags::Carry),
                (127, Flags::Carry),
                (127, Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_swap() {
        test_alu_op(
            AluOp::SWAP,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[Flags::empty(), Flags::Carry],
            &[
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (0, Flags::Zero),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (16, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (247, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (8, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
            ],
        );
    }

    // Bit Ops
    #[test]
    fn test_bit() {
        test_alu_op(
            AluOp::BIT,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0, 1, 2, 3, 4, 5, 6, 7],
            &[
                Flags::empty(),
                Flags::HalfCarry,
                Flags::Carry,
                Flags::HalfCarry | Flags::Carry,
            ],
            &[
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::HalfCarry),
                (1, Flags::HalfCarry),
                (1, Flags::HalfCarry | Flags::Carry),
                (1, Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (1, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::HalfCarry | Flags::Carry),
                (127, Flags::Zero | Flags::HalfCarry),
                (127, Flags::Zero | Flags::HalfCarry),
                (127, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (127, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::HalfCarry | Flags::Carry),
                (128, Flags::HalfCarry),
                (128, Flags::HalfCarry),
                (128, Flags::HalfCarry | Flags::Carry),
                (128, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry),
                (255, Flags::HalfCarry | Flags::Carry),
                (255, Flags::HalfCarry | Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_res() {
        test_alu_op(
            AluOp::RES,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0, 1, 2, 3, 4, 5, 6, 7],
            &[Flags::empty()],
            &[
                (0, Flags::empty()),
                (0, Flags::empty()),
                (0, Flags::empty()),
                (0, Flags::empty()),
                (0, Flags::empty()),
                (0, Flags::empty()),
                (0, Flags::empty()),
                (0, Flags::empty()),
                (0, Flags::empty()),
                (1, Flags::empty()),
                (1, Flags::empty()),
                (1, Flags::empty()),
                (1, Flags::empty()),
                (1, Flags::empty()),
                (1, Flags::empty()),
                (1, Flags::empty()),
                (126, Flags::empty()),
                (125, Flags::empty()),
                (123, Flags::empty()),
                (119, Flags::empty()),
                (111, Flags::empty()),
                (95, Flags::empty()),
                (63, Flags::empty()),
                (127, Flags::empty()),
                (128, Flags::empty()),
                (128, Flags::empty()),
                (128, Flags::empty()),
                (128, Flags::empty()),
                (128, Flags::empty()),
                (128, Flags::empty()),
                (128, Flags::empty()),
                (0, Flags::empty()),
                (254, Flags::empty()),
                (253, Flags::empty()),
                (251, Flags::empty()),
                (247, Flags::empty()),
                (239, Flags::empty()),
                (223, Flags::empty()),
                (191, Flags::empty()),
                (127, Flags::empty()),
            ],
        );
    }

    #[test]
    fn test_set() {
        test_alu_op(
            AluOp::SET,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0, 1, 2, 3, 4, 5, 6, 7],
            &[Flags::empty()],
            &[
                (1, Flags::empty()),
                (2, Flags::empty()),
                (4, Flags::empty()),
                (8, Flags::empty()),
                (16, Flags::empty()),
                (32, Flags::empty()),
                (64, Flags::empty()),
                (128, Flags::empty()),
                (1, Flags::empty()),
                (3, Flags::empty()),
                (5, Flags::empty()),
                (9, Flags::empty()),
                (17, Flags::empty()),
                (33, Flags::empty()),
                (65, Flags::empty()),
                (129, Flags::empty()),
                (127, Flags::empty()),
                (127, Flags::empty()),
                (127, Flags::empty()),
                (127, Flags::empty()),
                (127, Flags::empty()),
                (127, Flags::empty()),
                (127, Flags::empty()),
                (255, Flags::empty()),
                (129, Flags::empty()),
                (130, Flags::empty()),
                (132, Flags::empty()),
                (136, Flags::empty()),
                (144, Flags::empty()),
                (160, Flags::empty()),
                (192, Flags::empty()),
                (128, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
                (255, Flags::empty()),
            ],
        );
    }

    // Misc
    #[test]
    fn test_ccf() {
        test_alu_op(
            AluOp::CCF,
            &[0],
            &[0],
            &get_all_flag_combinations(),
            &[
                (0, Flags::Carry),
                (0, Flags::empty()),
                (0, Flags::Carry),
                (0, Flags::empty()),
                (0, Flags::Carry),
                (0, Flags::empty()),
                (0, Flags::Carry),
                (0, Flags::empty()),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero),
            ],
        );
    }

    #[test]
    fn test_cpl() {
        test_alu_op(
            AluOp::CPL,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0],
            &get_all_flag_combinations(),
            &[
                (255, Flags::Subtract | Flags::HalfCarry),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Subtract | Flags::HalfCarry),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Subtract | Flags::HalfCarry),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Subtract | Flags::HalfCarry),
                (255, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (255, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    255,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (255, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    255,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (255, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    255,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (255, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    255,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (254, Flags::Subtract | Flags::HalfCarry),
                (254, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (254, Flags::Subtract | Flags::HalfCarry),
                (254, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (254, Flags::Subtract | Flags::HalfCarry),
                (254, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (254, Flags::Subtract | Flags::HalfCarry),
                (254, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (254, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    254,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (254, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    254,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (254, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    254,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (254, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    254,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (128, Flags::Subtract | Flags::HalfCarry),
                (128, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Subtract | Flags::HalfCarry),
                (128, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Subtract | Flags::HalfCarry),
                (128, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Subtract | Flags::HalfCarry),
                (128, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (128, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    128,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (128, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    128,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (128, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    128,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (128, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    128,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (127, Flags::Subtract | Flags::HalfCarry),
                (127, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (127, Flags::Subtract | Flags::HalfCarry),
                (127, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (127, Flags::Subtract | Flags::HalfCarry),
                (127, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (127, Flags::Subtract | Flags::HalfCarry),
                (127, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (127, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    127,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (127, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    127,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (127, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    127,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (127, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    127,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (0, Flags::Subtract | Flags::HalfCarry),
                (0, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Subtract | Flags::HalfCarry),
                (0, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Subtract | Flags::HalfCarry),
                (0, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Subtract | Flags::HalfCarry),
                (0, Flags::Subtract | Flags::HalfCarry | Flags::Carry),
                (0, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    0,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (0, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    0,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (0, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    0,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
                (0, Flags::Zero | Flags::Subtract | Flags::HalfCarry),
                (
                    0,
                    Flags::Zero | Flags::Subtract | Flags::HalfCarry | Flags::Carry,
                ),
            ],
        );
    }

    #[test]
    fn test_scf() {
        test_alu_op(
            AluOp::SCF,
            &[0],
            &[0],
            &get_all_flag_combinations(),
            &[
                (0, Flags::Carry),
                (0, Flags::Carry),
                (0, Flags::Carry),
                (0, Flags::Carry),
                (0, Flags::Carry),
                (0, Flags::Carry),
                (0, Flags::Carry),
                (0, Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
                (0, Flags::Zero | Flags::Carry),
            ],
        );
    }

    #[test]
    fn test_daa() {
        test_alu_op(
            AluOp::DAA,
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &[0x00, 0x01, 0x7F, 0x80, 0xFF],
            &get_all_flag_combinations(),
            &[
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (0, Flags::Zero),
                (96, Flags::Carry),
                (6, Flags::empty()),
                (102, Flags::Carry),
                (0, Flags::Zero | Flags::Subtract),
                (160, Flags::Subtract | Flags::Carry),
                (250, Flags::Subtract),
                (154, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (1, Flags::empty()),
                (97, Flags::Carry),
                (7, Flags::empty()),
                (103, Flags::Carry),
                (1, Flags::Subtract),
                (161, Flags::Subtract | Flags::Carry),
                (251, Flags::Subtract),
                (155, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (133, Flags::empty()),
                (229, Flags::Carry),
                (127, Flags::Subtract),
                (31, Flags::Subtract | Flags::Carry),
                (121, Flags::Subtract),
                (25, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (128, Flags::empty()),
                (224, Flags::Carry),
                (134, Flags::empty()),
                (230, Flags::Carry),
                (128, Flags::Subtract),
                (32, Flags::Subtract | Flags::Carry),
                (122, Flags::Subtract),
                (26, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (101, Flags::Carry),
                (255, Flags::Subtract),
                (159, Flags::Subtract | Flags::Carry),
                (249, Flags::Subtract),
                (153, Flags::Subtract | Flags::Carry),
            ],
        );
    }
}
